apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-test
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: shared-storage
          mountPath: /data/shared1

    - name: nginx
      image: nginx
      volumeMounts:
        - name: shared-storage
          mountPath: /data/shared2

  volumes:
    - name : shared-storage
      emptyDir: {}
