apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: my-empty-dir
          mountPath: /data/shared1

    - name: nginx
      image: nginx
      volumeMounts:
        - name: my-empty-dir
          mountPath: /data/shared2

  volumes:
    - name: my-empty-dir
      emptyDir: {}
