apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod-wkr1
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - mountPath: /data/shared1
          name: my-host-path-volume
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data/shared2
          name: my-host-path-volume
  nodeSelector:
    disktype: scsi
  volumes:
    - name: my-host-path-volume
      hostPath:
        path: /home/data
        type: Directory
