apiVersion: v1
kind: Deployment
metadata:
  name: host-path-test
  labels:
    app: host-path-test-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: host-path-test-label

  template:
    metadata:
      labels:
        app: host-path-test-label
    spec:
      containers:
        - name: redis
          image: redis
          volumeMounts:
            - mountPath: /data/shared1
              name: my-host-path-volume

        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /data/shared2
              name: my-host-path-volume
  volumes:
    - name: my-host-path-volume
      hostPath:
        path: /home/data
        type: Directory
