apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    app: nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 172.31.0.20
    path: /home/nfs
    readOnly: false
