apiVersion: v1
kind: Deployment
metadata:
  name: pvc-nfs-deploy
spec:
  selector:
    matchLabels:
      app: dpl-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: dpl-nginx
    spec:
      containers:
      - name: myfrontend
        image: nginx
        volumeMounts:
            mountPath: "/var/www/html"
          - name: pvc-vol
  volumes:
    - name: pvc-vol
      persistentVolumeClaim:
        claimName: pvc-nfs
