apiVersion: v1
kind: Pod
metadata:
  name: pvc-nfs-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: pvc-vol
  volumes:
    - name: pvc-vol
      persistentVolumeClaim:
        claimName: pvc-nfs
