apiVersion: v1
kind: Pod
metadata:
  name: nfs-pvc-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
        - name: my-vol
          mountPath: "/var/www/html"
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: nfs-pvc
